# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convivencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanciones',
            name='Fecha_incorporacion',
        ),
    ]
