# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convivencia', '0004_tiposamonestaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposamonestaciones',
            options={'verbose_name': 'Tipo Ampnestaci\xf3n', 'verbose_name_plural': 'Tipo Amonestaciones'},
        ),
    ]
