# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='EquipoEducativo',
            field=models.ManyToManyField(to='centro.Profesores', verbose_name='Equipo Educativo'),
        ),
    ]
